//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.13 at 04:20:15 PM MSK 
//


package eu.solutions.a2.audit.ora112.schema;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AuditRecord" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Audit_Type" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                   &lt;element name="Session_Id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *                   &lt;element name="Proxy_SessionId" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *                   &lt;element name="StatementId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *                   &lt;element name="EntryId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *                   &lt;element name="Extended_Timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="Global_Uid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="DB_User" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Client_Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Ext_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="OS_User" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Userhost" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="OS_Process" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Terminal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Instance_Number" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *                   &lt;element name="Object_Schema" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Object_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Policy_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="New_Owner" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="New_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Action" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *                   &lt;element name="Stmt_Type" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *                   &lt;element name="TransactionId" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
 *                   &lt;element name="Returncode" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="Scn" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *                   &lt;element name="Comment_Text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="AuthPrivileges" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="OSPrivilege" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Grantee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Priv_Used" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="SesActions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Obj_Edition_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Priv_Granted" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="DBID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="Sql_Bind" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="BASE64Encoded" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Sql_Text" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="BASE64Encoded" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "version",
    "auditRecord"
})
@XmlRootElement(name = "Audit")
public class Audit {

    @XmlElement(name = "Version", required = true)
    protected String version;
    @XmlElement(name = "AuditRecord")
    protected List<Audit.AuditRecord> auditRecord;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the auditRecord property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the auditRecord property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuditRecord().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Audit.AuditRecord }
     * 
     * 
     */
    public List<Audit.AuditRecord> getAuditRecord() {
        if (auditRecord == null) {
            auditRecord = new ArrayList<Audit.AuditRecord>();
        }
        return this.auditRecord;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Audit_Type" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *         &lt;element name="Session_Id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
     *         &lt;element name="Proxy_SessionId" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
     *         &lt;element name="StatementId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
     *         &lt;element name="EntryId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
     *         &lt;element name="Extended_Timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="Global_Uid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DB_User" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Client_Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Ext_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="OS_User" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Userhost" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="OS_Process" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Terminal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Instance_Number" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
     *         &lt;element name="Object_Schema" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Object_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Policy_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="New_Owner" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="New_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Action" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
     *         &lt;element name="Stmt_Type" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
     *         &lt;element name="TransactionId" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
     *         &lt;element name="Returncode" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="Scn" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
     *         &lt;element name="Comment_Text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="AuthPrivileges" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="OSPrivilege" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Grantee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Priv_Used" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="SesActions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Obj_Edition_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Priv_Granted" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="DBID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="Sql_Bind" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="BASE64Encoded" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Sql_Text" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="BASE64Encoded" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "auditType",
        "sessionId",
        "proxySessionId",
        "statementId",
        "entryId",
        "extendedTimestamp",
        "globalUid",
        "dbUser",
        "clientId",
        "extName",
        "osUser",
        "userhost",
        "osProcess",
        "terminal",
        "instanceNumber",
        "objectSchema",
        "objectName",
        "policyName",
        "newOwner",
        "newName",
        "action",
        "stmtType",
        "transactionId",
        "returncode",
        "scn",
        "commentText",
        "authPrivileges",
        "osPrivilege",
        "grantee",
        "privUsed",
        "sesActions",
        "objEditionName",
        "privGranted",
        "dbid",
        "sqlBind",
        "sqlText"
    })
    public static class AuditRecord {

        @XmlElement(name = "Audit_Type")
        @XmlSchemaType(name = "unsignedShort")
        protected int auditType;
        @XmlElement(name = "Session_Id")
        @XmlSchemaType(name = "unsignedInt")
        protected Long sessionId;
        @XmlElement(name = "Proxy_SessionId")
        @XmlSchemaType(name = "unsignedInt")
        protected Long proxySessionId;
        @XmlElement(name = "StatementId")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger statementId;
        @XmlElement(name = "EntryId")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger entryId;
        @XmlElement(name = "Extended_Timestamp", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar extendedTimestamp;
        @XmlElement(name = "Global_Uid")
        protected String globalUid;
        @XmlElement(name = "DB_User")
        protected String dbUser;
        @XmlElement(name = "Client_Id")
        protected String clientId;
        @XmlElement(name = "Ext_Name")
        protected String extName;
        @XmlElement(name = "OS_User")
        protected String osUser;
        @XmlElement(name = "Userhost")
        protected String userhost;
        @XmlElement(name = "OS_Process")
        protected String osProcess;
        @XmlElement(name = "Terminal")
        protected String terminal;
        @XmlElement(name = "Instance_Number")
        @XmlSchemaType(name = "unsignedShort")
        protected Integer instanceNumber;
        @XmlElement(name = "Object_Schema")
        protected String objectSchema;
        @XmlElement(name = "Object_Name")
        protected String objectName;
        @XmlElement(name = "Policy_Name")
        protected String policyName;
        @XmlElement(name = "New_Owner")
        protected String newOwner;
        @XmlElement(name = "New_Name")
        protected String newName;
        @XmlElement(name = "Action")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger action;
        @XmlElement(name = "Stmt_Type")
        @XmlSchemaType(name = "unsignedShort")
        protected Integer stmtType;
        @XmlElement(name = "TransactionId", type = String.class)
        @XmlJavaTypeAdapter(HexBinaryAdapter.class)
        @XmlSchemaType(name = "hexBinary")
        protected byte[] transactionId;
        @XmlElement(name = "Returncode")
        protected BigInteger returncode;
        @XmlElement(name = "Scn")
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger scn;
        @XmlElement(name = "Comment_Text")
        protected String commentText;
        @XmlElement(name = "AuthPrivileges")
        protected String authPrivileges;
        @XmlElement(name = "OSPrivilege")
        protected String osPrivilege;
        @XmlElement(name = "Grantee")
        protected String grantee;
        @XmlElement(name = "Priv_Used")
        protected BigInteger privUsed;
        @XmlElement(name = "SesActions")
        protected String sesActions;
        @XmlElement(name = "Obj_Edition_Name")
        protected String objEditionName;
        @XmlElement(name = "Priv_Granted")
        protected BigInteger privGranted;
        @XmlElement(name = "DBID")
        protected BigInteger dbid;
        @XmlElement(name = "Sql_Bind")
        protected Audit.AuditRecord.SqlBind sqlBind;
        @XmlElement(name = "Sql_Text")
        protected Audit.AuditRecord.SqlText sqlText;

        /**
         * Gets the value of the auditType property.
         * 
         */
        public int getAuditType() {
            return auditType;
        }

        /**
         * Sets the value of the auditType property.
         * 
         */
        public void setAuditType(int value) {
            this.auditType = value;
        }

        /**
         * Gets the value of the sessionId property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getSessionId() {
            return sessionId;
        }

        /**
         * Sets the value of the sessionId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setSessionId(Long value) {
            this.sessionId = value;
        }

        /**
         * Gets the value of the proxySessionId property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getProxySessionId() {
            return proxySessionId;
        }

        /**
         * Sets the value of the proxySessionId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setProxySessionId(Long value) {
            this.proxySessionId = value;
        }

        /**
         * Gets the value of the statementId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getStatementId() {
            return statementId;
        }

        /**
         * Sets the value of the statementId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setStatementId(BigInteger value) {
            this.statementId = value;
        }

        /**
         * Gets the value of the entryId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getEntryId() {
            return entryId;
        }

        /**
         * Sets the value of the entryId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setEntryId(BigInteger value) {
            this.entryId = value;
        }

        /**
         * Gets the value of the extendedTimestamp property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getExtendedTimestamp() {
            return extendedTimestamp;
        }

        /**
         * Sets the value of the extendedTimestamp property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setExtendedTimestamp(XMLGregorianCalendar value) {
            this.extendedTimestamp = value;
        }

        /**
         * Gets the value of the globalUid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGlobalUid() {
            return globalUid;
        }

        /**
         * Sets the value of the globalUid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGlobalUid(String value) {
            this.globalUid = value;
        }

        /**
         * Gets the value of the dbUser property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDBUser() {
            return dbUser;
        }

        /**
         * Sets the value of the dbUser property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDBUser(String value) {
            this.dbUser = value;
        }

        /**
         * Gets the value of the clientId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClientId() {
            return clientId;
        }

        /**
         * Sets the value of the clientId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClientId(String value) {
            this.clientId = value;
        }

        /**
         * Gets the value of the extName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtName() {
            return extName;
        }

        /**
         * Sets the value of the extName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtName(String value) {
            this.extName = value;
        }

        /**
         * Gets the value of the osUser property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOSUser() {
            return osUser;
        }

        /**
         * Sets the value of the osUser property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOSUser(String value) {
            this.osUser = value;
        }

        /**
         * Gets the value of the userhost property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserhost() {
            return userhost;
        }

        /**
         * Sets the value of the userhost property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserhost(String value) {
            this.userhost = value;
        }

        /**
         * Gets the value of the osProcess property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOSProcess() {
            return osProcess;
        }

        /**
         * Sets the value of the osProcess property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOSProcess(String value) {
            this.osProcess = value;
        }

        /**
         * Gets the value of the terminal property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTerminal() {
            return terminal;
        }

        /**
         * Sets the value of the terminal property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTerminal(String value) {
            this.terminal = value;
        }

        /**
         * Gets the value of the instanceNumber property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getInstanceNumber() {
            return instanceNumber;
        }

        /**
         * Sets the value of the instanceNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setInstanceNumber(Integer value) {
            this.instanceNumber = value;
        }

        /**
         * Gets the value of the objectSchema property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getObjectSchema() {
            return objectSchema;
        }

        /**
         * Sets the value of the objectSchema property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setObjectSchema(String value) {
            this.objectSchema = value;
        }

        /**
         * Gets the value of the objectName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getObjectName() {
            return objectName;
        }

        /**
         * Sets the value of the objectName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setObjectName(String value) {
            this.objectName = value;
        }

        /**
         * Gets the value of the policyName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPolicyName() {
            return policyName;
        }

        /**
         * Sets the value of the policyName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPolicyName(String value) {
            this.policyName = value;
        }

        /**
         * Gets the value of the newOwner property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNewOwner() {
            return newOwner;
        }

        /**
         * Sets the value of the newOwner property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNewOwner(String value) {
            this.newOwner = value;
        }

        /**
         * Gets the value of the newName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNewName() {
            return newName;
        }

        /**
         * Sets the value of the newName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNewName(String value) {
            this.newName = value;
        }

        /**
         * Gets the value of the action property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getAction() {
            return action;
        }

        /**
         * Sets the value of the action property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setAction(BigInteger value) {
            this.action = value;
        }

        /**
         * Gets the value of the stmtType property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getStmtType() {
            return stmtType;
        }

        /**
         * Sets the value of the stmtType property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setStmtType(Integer value) {
            this.stmtType = value;
        }

        /**
         * Gets the value of the transactionId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public byte[] getTransactionId() {
            return transactionId;
        }

        /**
         * Sets the value of the transactionId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransactionId(byte[] value) {
            this.transactionId = value;
        }

        /**
         * Gets the value of the returncode property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getReturncode() {
            return returncode;
        }

        /**
         * Sets the value of the returncode property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setReturncode(BigInteger value) {
            this.returncode = value;
        }

        /**
         * Gets the value of the scn property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getScn() {
            return scn;
        }

        /**
         * Sets the value of the scn property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setScn(BigInteger value) {
            this.scn = value;
        }

        /**
         * Gets the value of the commentText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCommentText() {
            return commentText;
        }

        /**
         * Sets the value of the commentText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCommentText(String value) {
            this.commentText = value;
        }

        /**
         * Gets the value of the authPrivileges property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthPrivileges() {
            return authPrivileges;
        }

        /**
         * Sets the value of the authPrivileges property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthPrivileges(String value) {
            this.authPrivileges = value;
        }

        /**
         * Gets the value of the osPrivilege property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOSPrivilege() {
            return osPrivilege;
        }

        /**
         * Sets the value of the osPrivilege property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOSPrivilege(String value) {
            this.osPrivilege = value;
        }

        /**
         * Gets the value of the grantee property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGrantee() {
            return grantee;
        }

        /**
         * Sets the value of the grantee property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGrantee(String value) {
            this.grantee = value;
        }

        /**
         * Gets the value of the privUsed property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPrivUsed() {
            return privUsed;
        }

        /**
         * Sets the value of the privUsed property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPrivUsed(BigInteger value) {
            this.privUsed = value;
        }

        /**
         * Gets the value of the sesActions property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSesActions() {
            return sesActions;
        }

        /**
         * Sets the value of the sesActions property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSesActions(String value) {
            this.sesActions = value;
        }

        /**
         * Gets the value of the objEditionName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getObjEditionName() {
            return objEditionName;
        }

        /**
         * Sets the value of the objEditionName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setObjEditionName(String value) {
            this.objEditionName = value;
        }

        /**
         * Gets the value of the privGranted property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPrivGranted() {
            return privGranted;
        }

        /**
         * Sets the value of the privGranted property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPrivGranted(BigInteger value) {
            this.privGranted = value;
        }

        /**
         * Gets the value of the dbid property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getDBID() {
            return dbid;
        }

        /**
         * Sets the value of the dbid property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setDBID(BigInteger value) {
            this.dbid = value;
        }

        /**
         * Gets the value of the sqlBind property.
         * 
         * @return
         *     possible object is
         *     {@link Audit.AuditRecord.SqlBind }
         *     
         */
        public Audit.AuditRecord.SqlBind getSqlBind() {
            return sqlBind;
        }

        /**
         * Sets the value of the sqlBind property.
         * 
         * @param value
         *     allowed object is
         *     {@link Audit.AuditRecord.SqlBind }
         *     
         */
        public void setSqlBind(Audit.AuditRecord.SqlBind value) {
            this.sqlBind = value;
        }

        /**
         * Gets the value of the sqlText property.
         * 
         * @return
         *     possible object is
         *     {@link Audit.AuditRecord.SqlText }
         *     
         */
        public Audit.AuditRecord.SqlText getSqlText() {
            return sqlText;
        }

        /**
         * Sets the value of the sqlText property.
         * 
         * @param value
         *     allowed object is
         *     {@link Audit.AuditRecord.SqlText }
         *     
         */
        public void setSqlText(Audit.AuditRecord.SqlText value) {
            this.sqlText = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="BASE64Encoded" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class SqlBind {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "BASE64Encoded")
            protected Boolean base64Encoded;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the base64Encoded property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isBASE64Encoded() {
                return base64Encoded;
            }

            /**
             * Sets the value of the base64Encoded property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setBASE64Encoded(Boolean value) {
                this.base64Encoded = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="BASE64Encoded" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class SqlText {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "BASE64Encoded")
            protected Boolean base64Encoded;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the base64Encoded property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isBASE64Encoded() {
                return base64Encoded;
            }

            /**
             * Sets the value of the base64Encoded property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setBASE64Encoded(Boolean value) {
                this.base64Encoded = value;
            }

        }

    }

}
