//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.13 at 04:20:15 PM MSK 
//


package eu.solutions.a2.audit.ora112.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.solutions.a2.audit.ora112.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.solutions.a2.audit.ora112.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Audit }
     * 
     */
    public Audit createAudit() {
        return new Audit();
    }

    /**
     * Create an instance of {@link Audit.AuditRecord }
     * 
     */
    public Audit.AuditRecord createAuditAuditRecord() {
        return new Audit.AuditRecord();
    }

    /**
     * Create an instance of {@link Audit.AuditRecord.SqlBind }
     * 
     */
    public Audit.AuditRecord.SqlBind createAuditAuditRecordSqlBind() {
        return new Audit.AuditRecord.SqlBind();
    }

    /**
     * Create an instance of {@link Audit.AuditRecord.SqlText }
     * 
     */
    public Audit.AuditRecord.SqlText createAuditAuditRecordSqlText() {
        return new Audit.AuditRecord.SqlText();
    }

}
