//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.13 at 04:20:15 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xmlns.oracle.com/oracleas/schema/dbserver_audittrail-11_2.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.solutions.a2.audit.ora112.schema;
